kind = "web"
previewPath = "/"
title = "LUAU IDE"
version = "1.0.0"
id = "artifacts/luau-ide"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25349

[services.development]
run = "pnpm --filter @workspace/luau-ide run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/luau-ide", "run", "build" ]
publicDir = "artifacts/luau-ide/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25349"
BASE_PATH = "/"
